using System;
using System.Collections.Generic;
using System.IO;
using UnityEngine;

/// <summary>
///  A helper class to read and save to the photo database
/// </summary>
public class DiskIOWorker
{
    public static void SavePhotoAndMetadata(Texture2D photo, PhotoMetadata metadata)
    {
        string folderPath = Path.Combine(Application.persistentDataPath, "Photos");

        if (!Directory.Exists(folderPath))
        {
            Directory.CreateDirectory(folderPath);
            Debug.Log("📁 Created new Photos directory at: " + folderPath);
        }

        // --- SAVE THE PNG IMAGE ---
        // We use the exact ID generated by the metadata so the JSON and PNG names match perfectly
        string imagePath = Path.Combine(folderPath, metadata.photoID + ".png");
        byte[] imageBytes = photo.EncodeToPNG();
        File.WriteAllBytes(imagePath, imageBytes);

        // --- SAVE THE JSON DATABASE ---
        string jsonPath = Path.Combine(folderPath, "photos_metadata.json");
        PhotoDatabase database = new PhotoDatabase();

        if (File.Exists(jsonPath))
        {
            string existingJson = File.ReadAllText(jsonPath);
            database = JsonUtility.FromJson<PhotoDatabase>(existingJson);
        }
        // Safety check in case the JSON was corrupted or empty
        if (database == null) database = new PhotoDatabase();
        if (database.allPhotos == null) database.allPhotos = new List<PhotoMetadata>();

        // Add our brand new photo's math data to the list
        database.allPhotos.Add(metadata);

        // Convert the updated list back into JSON text (the 'true' makes it pretty and readable)
        string newJson = JsonUtility.ToJson(database, true);
        
        // Save the updated database to the hard drive
        File.WriteAllText(jsonPath, newJson);

        Debug.Log($"SUCCESS: Photo and Metadata saved to disk! ID: {metadata.photoID}");
    }
}
